
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  username: rails_dev
  password: <%= ENV["dev_password"] %>


development:
  <<: *default
  database: job_board_development

test:
  <<: *default
  database: job_board_test
